services:
  backend-for-frontend:
    build:
      context: services/backend-for-frontend-java
      dockerfile: Dockerfile
      args:
        - OTEL_JAVA_AGENT_VERSION
    image: backend-for-frontend-java:latest
    ports:
      - "10115"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_EXPORTER_OTLP_HEADERS
      - OTEL_SERVICE_NAME=backend-for-frontend
      - OTEL_RESOURCE_ATTRIBUTES=build.id=local-build 
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:10115/actuator/health || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 24

  image-picker:
    build:
      context: services/image-picker-java
      dockerfile: Dockerfile
      args:
        - OTEL_JAVA_AGENT_VERSION
    image: image-picker-java:latest
    ports:
      - "10116"
    environment:
      - BUCKET_NAME
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_EXPORTER_OTLP_HEADERS
      - OTEL_SERVICE_NAME=image-picker-java

  meminator:
    build:
      context: services/meminator-java
      dockerfile: Dockerfile
      args:
        - OTEL_JAVA_AGENT_VERSION
    image: meminator-java:latest
    ports:
      - "10117"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_EXPORTER_OTLP_HEADERS
      - OTEL_SERVICE_NAME=meminator-java

  phrase-picker:
    build:
      context: services/phrase-picker-java
      dockerfile: Dockerfile
      args:
        - OTEL_JAVA_AGENT_VERSION
    image: phrase-picker-java:latest
    ports:
      - "10118"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_EXPORTER_OTLP_HEADERS
      - OTEL_SERVICE_NAME=phrase-picker-java

  web:
    build:
      context: services/web
      dockerfile: Dockerfile
      args:
        - HONEYCOMB_API_KEY
    image: web:latest
    # volumes: # uncomment this for faster development on the frontend
    #   - ./services/web/dist:/usr/share/nginx/html # Mount directory containing static files -- only do this for development
    ports:
      - "10114:10114"
    depends_on:
      backend-for-frontend:
        condition: service_healthy
      image-picker:
        condition: service_started
      meminator:
        condition: service_started
      phrase-picker:
        condition: service_started
